language: php

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq clamav-daemon
  - sudo freshclam
  - sudo /etc/init.d/clamav-daemon start

install:
  - composer install

php:
  - 5.6
  - 7.0

script:
  - vendor/bin/phpunit